<DraggableWidget>:
    size_hint:None,None



<StickMan@RelativeLayout>
    size_hint: None,None
    size:48,48
    canvas:
        Color:
            rgba:1,0,0,1
        PushMatrix:
        Rotate:
            angle:90
            axis:0,0,1
            origin:24,24

        Line:
            circle:24,38,5
        PopMatrix:
        Line:
            points:24,33,24,15
        Line:
            points:14,5,24,15
        Line:
            points:35,5,24,15
